### ISSUE TITLE
recipe files have parameters defined multiple times

### ISSUE THREAD

**Issue by ablot** [BaselLaserMouse/StitchIt#113]
In the recipe file pixel size and number of line/rows are defined twice. Should they be merged or do you have a reason to keep 2 versions?

Example extract of recipe file:
```
Tile: {nRows: 566.0, nColumns: 566.0}
VoxelSize: {X: 1.668, Y: 1.668, Z: 6.666666666666667}
ScannerSettings:
  pixelsPerLine: 566.0
  linesPerFrame: 566.0
  micronsBetweenOpticalPlanes: 6.666666666666667
  micronsPerPixel_cols: 1.668
  micronsPerPixel_rows: 1.668
```
